spring:
    application:
        name: service-product
    config:
        import: "optional:configserver:"
    cloud:
        config:
            uri: http://localhost:8081
            username: root
            password: s3cr3t
